### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by tkokto** [huangjie-nlp/CasRel#1]
您好，训练了60个epoch后，运行test.py ，试了几个训练集中的句子，预测的triple_result是空的，但是在eval_result下的json中能看到验证集的结果，里面能看到预测出的数据，是啥原因呢？感谢！

**Comment by huangjie-nlp** [comment]
你看看 把CLS 和 SEP 改成 [CLS] 和 [SEP]

**Comment by huangjie-nlp** [comment]
> 您好，训练了60个epoch后，运行test.py ，试了几个训练集中的句子，预测的triple_result是空的，但是在eval_result下的json中能看到验证集的结果，里面能看到预测出的数据，是啥原因呢？感谢！

你看看 把CLS 和 SEP 改成 [CLS] 和 [SEP]

**Comment by tkokto** [comment]
> > 您好，训练了60个epoch后，运行test.py ，试了几个训练集中的句子，预测的triple_result是空的，但是在eval_result下的json中能看到验证集的结果，里面能看到预测出的数据，是啥原因呢？感谢！
> 
> 你看看 把CLS 和 SEP 改成 [CLS] 和 [SEP]

ok,我试一下
